In [ ]:
# 数分第3课作业

In [1]:
import numpy as np
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [2]:
# sum 求和
print(np.sum(a))

210


In [3]:
print(np.sum(a[1,:])) #切片求和

40


In [4]:
print(np.sum(a[:,3]))

46


In [5]:
# average 平均水平 一般水准
# mean 平均数 均值
print(np.average(a))
print(np.mean(a))

10.5
10.5


In [6]:
print(np.prod(a))  # 乘积

2432902008176640000


In [7]:
print(np.cumsum(a)) # 累积和

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]


In [8]:
print(np.cumprod(a)) # 累积乘积

[                  1                   2                   6
                  24                 120                 720
                5040               40320              362880
             3628800            39916800           479001600
          6227020800         87178291200       1307674368000
      20922789888000     355687428096000    6402373705728000
  121645100408832000 2432902008176640000]


In [9]:
print(np.median(a)) # 中位数

10.5


In [10]:
print(np.var(a)) # 方差 先计算平均值 10.5 ((1-10.5)**2 ...(20-10.5)**2) 再算平方

33.25


In [11]:
print(np.std(a)) # 标准差 方差的平方根

5.766281297335398


In [13]:
print(np.sqrt(33.25)) # sqrt 平方根

5.766281297335398


In [16]:
data = np.array([1,5,8,9,1,23,4,5,6,87])
ton = np.percentile(data,50) # 百分位数
print(ton)
# print(np.quantile(data,50)) # 分位数 与百分位传参不同！

5.5


In [25]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
ton = np.quantile(data,.75) # 百分位数 注意第二个参数小于[1,1]
print(ton)

7.75


In [32]:
import random
random.seed(10) # 设置随机数生成器的种子的函数 如果不指定种 seed会默认使用系统时间戳
print(random.random()) # 生成一个随机数

0.5714025946899135


In [33]:
print(np.random.rand(20)) # 参数：随机数个数 [0,1) 0到1 不包含1的数 左闭右开

[0.52894873 0.14447948 0.35051788 0.76913413 0.60296366 0.50304101
 0.01217467 0.12706952 0.78034385 0.32264521 0.09795078 0.98717326
 0.60329322 0.03272994 0.32222782 0.26515522 0.16162479 0.34384131
 0.20899186 0.88142655]


In [34]:
a = np.random.randint(3) # 生成范围内的随机整数
print(a)

1


In [37]:
to = []
for i in range(30):
    a = np.random.randint(3) # 0，1，2
    to.append(a)
print(to)

[2, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 0, 2, 1, 2, 2, 0, 0, 1, 2, 2, 0, 0, 1, 2, 0, 1, 0]


In [38]:
np.random.randint(1,5,size=(2,3))

array([[4, 1, 2],
       [4, 1, 1]], dtype=int32)

In [41]:
b = np.random.random(10)*100
b
b.astype(int) # 转换为int整数

array([15, 20, 34,  8, 36, 12, 19, 74,  7, 64])

In [45]:
a = np.random.randn(3,4)  # 生成标准正态分布（高斯分布）的随机数组 标准差略为1 均值为略0
a

array([[-0.68642842, -0.11753204, -1.14308455,  0.52859064],
       [ 1.33926054,  1.08331388, -1.84128427, -0.17717089],
       [ 0.06038068,  0.20917902,  1.36592032, -0.32676248]])

In [47]:
print(np.std(a))
print(np.mean(a))

0.9341950699695638
0.024531869844104593


In [50]:
a = np.random.choice(5,(2,3)) # 参数1 可以是列表 也可以是字符（列表）
print(a) # range(5) 中拿随机数 生成2行3列的二维数组

[[2 1 0]
 [3 4 1]]


In [51]:
a = np.random.choice(['a','b','c','d','e'],(2,3)) # 参数1 可以是列表 也可以是字符（列表）
print(a) # range(5) 中拿随机数 生成2行3列的二维数组

[['c' 'a' 'c']
 ['b' 'c' 'd']]


In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.random.shuffle(a) # 直接在原数据上打乱数组的顺序
print(a)

[1 5 6 9 0 3 7 4 8 2]


In [61]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
c =np.random.shuffle(b)  # 多维数组打乱？？？
print(c)

None


In [66]:
c = np.random.permutation(10) # 返回一个数组的随机排列
c

array([4, 5, 8, 2, 3, 9, 0, 6, 1, 7], dtype=int32)

In [68]:
c = np.random.permutation(np.array([1,2,3,4,5,6,7])) # 返回一个数组的随机排列
c

array([1, 2, 5, 7, 3, 4, 6])